#!/usr/bin/env sh

# Gradle start up script for POSIX generated by minimal template

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

DEFAULT_JVM_OPTS=""

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

while [ "$1" != "" ] ; do
    case $1 in
        -d|--debug)
            set -x
            ;;
        *)
            break
            ;;
    esac
    shift
 done

APP_HOME=`pwd -P`

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
    die "ERROR: Gradle wrapper jar not found at $CLASSPATH"
fi

JAVA_CMD="java"

if [ -n "$JAVA_HOME" ] ; then
    JAVA_CMD="$JAVA_HOME/bin/java"
fi

exec "$JAVA_CMD" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
